# Generated by Django 4.2.11 on 2024-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="contry",
            field=models.CharField(default="Unknown", max_length=64),
        ),
        migrations.AddField(
            model_name="worker",
            name="mobile",
            field=models.CharField(default="Unknown", max_length=64),
        ),
        migrations.AddField(
            model_name="worker",
            name="sity",
            field=models.CharField(default="Unknown", max_length=64),
        ),
    ]
