# Generated by Django 4.2.11 on 2024-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_worker_contry_worker_mobile_worker_sity"),
    ]

    operations = [
        migrations.RemoveField(model_name="worker", name="contry",),
        migrations.RemoveField(model_name="worker", name="mobile",),
        migrations.RemoveField(model_name="worker", name="sity",),
        migrations.AddField(
            model_name="myuser",
            name="contry",
            field=models.CharField(default="Unknown", max_length=64),
        ),
        migrations.AddField(
            model_name="myuser",
            name="mobile",
            field=models.CharField(default="Unknown", max_length=64),
        ),
        migrations.AddField(
            model_name="myuser",
            name="sity",
            field=models.CharField(default="Unknown", max_length=64),
        ),
    ]
