# Generated by Django 4.2.11 on 2024-05-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_worker_contry_remove_worker_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="contry",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="mobile",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="sity",
            field=models.CharField(default="", max_length=64),
        ),
    ]
