# Generated by Django 4.2.11 on 2024-05-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_myuser_contry_alter_myuser_mobile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser", old_name="contry", new_name="city",
        ),
        migrations.RenameField(
            model_name="myuser", old_name="sity", new_name="country",
        ),
    ]
