# Generated by Django 4.2.11 on 2024-04-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="marketplace_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.marketplace"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.statusorder"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="worker_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="order_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="complatedassets",
            name="order_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
