# Generated by Django 4.2.11 on 2024-05-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_information_due_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderhistory",
            name="description",
            field=models.CharField(default="", max_length=512),
        ),
    ]
