# Generated by Django 4.2.11 on 2024-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderhistory_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="complatedassets",
            name="files",
            field=models.FileField(default=None, upload_to=""),
        ),
        migrations.AddField(
            model_name="complatedassets",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
