# Generated by Django 4.2.11 on 2024-05-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_complatedassets_files_complatedassets_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="sourseassets", name="max_val_face",),
        migrations.RemoveField(model_name="sourseassets", name="num_face",),
        migrations.RemoveField(model_name="sourseassets", name="rate_per_face",),
        migrations.AddField(
            model_name="sourseassets",
            name="files",
            field=models.FileField(default=None, upload_to=""),
        ),
        migrations.AddField(
            model_name="sourseassets",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
