# Generated by Django 4.2.11 on 2024-05-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_sourseassets_max_val_face_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complatedassets", old_name="files", new_name="complated_files",
        ),
        migrations.RenameField(
            model_name="sourseassets", old_name="files", new_name="sourse_files",
        ),
    ]
