# Generated by Django 4.2.11 on 2024-05-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_rename_files_complatedassets_complated_files_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourseassets",
            name="sourse_files",
            field=models.FileField(default=None, upload_to="media/%Y/%m/%d/"),
        ),
    ]
