# Generated by Django 4.2.11 on 2024-05-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_sourseassets_sourse_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourseassets",
            name="sourse_files",
            field=models.FileField(upload_to="media/%Y/%m/%d/"),
        ),
    ]
