# Generated by Django 4.2.11 on 2024-05-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_sourseassets_sourse_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourseassets",
            name="order_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
