# Generated by Django 4.2.11 on 2024-06-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_sourseassets_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourseassets",
            name="file_extension",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="sourseassets",
            name="size_file",
            field=models.IntegerField(default=""),
        ),
    ]
